# This is a basic workflow to help you get started with Actions

name: Production Deploy

# Controls when the workflow will run
on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download-release-jar:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          
      # Runs a single command using the runners shell
      - name: Download Previous Artifact
        uses: alextompkins/download-prior-artifact@v1.1.1
        with:
         name: mq-test
         path: ${{ github.repository }}
         repo: ${{ github.repository }}
         commitHash: 4151927
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Copy File
        uses: RomanosTrechlis/actions-copy-files@1.0

        with:
          source-files: /home/runner/work/ci-cd/ci-cd/ghosharijit1986/ci-cd/mq-test-1.0.0-SNAPSHOT-mule-application-4151927.jar
          destination-username: ghosharijit1986
          destination-repository: ci-cd
          destination-branch: main
        env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


       
